Add new homepage based on wireframe
Miss-placed/DECLASSIFIED pull request #436
Opened 2024-11-05 13:24 UTC by sol3uk

TODO:
Styling
Work out any possible issues with the old ID system and links that may need redirecting to the "/map" url.
Find any bugs before merging

2024-11-05 13:30 UTC, Odinnh commented
i'd suggest styling the homepage with darkmode as default
make use of the css vars pls 😘

2024-12-17 12:05 UTC, Odinnh requested changes
i do not agree with the ditching of general styling for text...

2024-12-17 12:17 UTC, sol3uk commented
@Odinnh what do you mean sorry? I'm just not going to use Material UI text theming, as it's very clunky and manual. Pure CSS is easier and better.

2024-12-17 12:27 UTC, Odinnh commented
@sol3uk Correction, it looked like you changed some variables i set. this was not the case. other than that it looks allright to me  [(talking about commit c139354) ](https://arc.net/l/quote/yxrptefi)

2024-12-17 12:29 UTC, sol3uk commented
Yeah I've left the variables as they are. The main issue (besides the others) with Mui theming is that it doesn't accept CSS vars 🙄

2025-01-04 15:42 UTC, Odinnh commented
lgtm
👌

2025-01-04 15:43 UTC, merged